version: '2'
services:
  db:
    image: postgres
  web:
    build: "."
    command: mix compile; mix phoenix.server
    environment:
      MIX_ENV: "prod"
    ports:
      - "4000:4000"
    depends_on:
      - db
